spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  mustache:
    suffix: .html
#  datasource:
#    url: jdbc:mysql://localhost:3306/myweb
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver