INSERT INTO USER (USER_SEQ , USER_ID, PASSWORD, EMAIL) VALUES (1, 'aa', 'aa', 'a@a.com')
INSERT INTO USER (USER_SEQ , USER_ID, PASSWORD, EMAIL) VALUES (2, 'bb', 'bb', 'b@b.com')
INSERT INTO USER (USER_SEQ , USER_ID, PASSWORD, EMAIL) VALUES (3, 'cc', 'cc', 'c@c.com')


INSERT INTO BOARD (BOARD_SEQ , TITLE, LOCATION, IMG , DESCRIPTION, REPORTING_DATE, USER_SEQ) VALUES (1, '가게1', '서울', 'img' , '설명1', CURRENT_TIMESTAMP, 1)

INSERT INTO BOARD (BOARD_SEQ , TITLE, LOCATION, IMG , DESCRIPTION, REPORTING_DATE, USER_SEQ) VALUES (2, '가게2', '부산', 'img' , '설명2', CURRENT_TIMESTAMP, 1)

INSERT INTO BOARD (BOARD_SEQ , TITLE, LOCATION, IMG , DESCRIPTION, REPORTING_DATE, USER_SEQ) VALUES (3, '가게3', '대구', 'img' , '설명3', CURRENT_TIMESTAMP, 1)

INSERT INTO BOARD (BOARD_SEQ , TITLE, LOCATION, IMG , DESCRIPTION, REPORTING_DATE, USER_SEQ) VALUES (4, '가게4', '대전', 'img' , '설명4', CURRENT_TIMESTAMP, 2)

