INSERT INTO BOARD (BOARD_SEQ , TITLE, LOCATION, IMG , DESCRIPTION, REPORTING_DATE) VALUES (1, '제목1', '서울', 'img' , '설명1', CURRENT_TIMESTAMP)

INSERT INTO BOARD (BOARD_SEQ , TITLE, LOCATION, IMG , DESCRIPTION, REPORTING_DATE) VALUES (2, '제목2', '부산', 'img' , '설명2', CURRENT_TIMESTAMP)

